name: Hello World Workflow

on:
  push:
    branches: [ main, branch_01022026 ]
  pull_request:
    branches: [ main, branch_01022026 ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
